name: Railway Deploy

on:
  push:
    # Reminder: Make sure the `branches` list only contain the name of main
    # branch! Usually, the main branch name is either `master` or `main`.
    # Check the list of branches of your repository via GitHub Web interface or
    # use `git branch -av` command in your shell.

    # This event trigger will only run the workflow whenever there are new
    # commits pushed to the main branch. Therefore, the deployed app that
    # will be accessed by users will be based on the latest version of the
    # main branch.
    branches:
      - main

jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Railway CLI
        run: |
          npm i -g @railway/cli
      - name: Deploy to Railway
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}